services:
  - type: web
    name: traffix-ai
    env: docker
    region: oregon 
    plan: free
    branch: main
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TOMTOM_API_KEY
        sync: false
      - key: VITE_TOMTOM_API_KEY
        sync: false
